export const CHANGE_FORM_NAME = 'CHANGE_FORM_NAME';
export const CHANGE_FORM_COUNT = 'CHANGE_FORM_COUNT';

export const INIT_APP = 'INIT_APP';



export const SELECT_EQUIPMENT = 'SELECT_EQUIPMENT';



export const UPDATE_OUTPUT_BUILDING = 'UPDATE_OUTPUT_BUILDING';
export const UPDATE_OUTPUT_EQUIPMENT = 'UPDATE_OUTPUT_EQUIPMENT';

